import { Inter } from "next/font/google";
import "./globals.css";
import CodemberTitle from "./components/CodemberTitle";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	//THIS IS FOR THE BACKGROUND ANIMATION
	/* document.body.addEventListener("pointermove", (e) => {
		const { currentTarget: el, clientX: x, clientY: y } = e;
		const { top: t, left: l, width: w, height: h } = el.getBoundingClientRect();
		el.style.setProperty("--posX", x - l - w / 2);
		el.style.setProperty("--posY", y - t - h / 2);
	}); */

	return (
		<html lang="en">
			<body className={inter.className}>
				<div className="interlaced"></div>
				<div className="max-w-6xl m-auto">
					<CodemberTitle />
					{children}
				</div>
			</body>
		</html>
	);
}
